### ISSUE TITLE
an example code how to make it a game human vs comp or human vs human

### ISSUE THREAD

**Issue by sugizo** [atw1020/sente#31]
on python module chess https://github.com/niklasf/python-chess, the owner include the link for example how to create their creation useful with a game human vs comp or human vs human
https://jupyter.brynmawr.edu/services/public/dblank/CS371%20Cognitive%20Science/2016-Fall/Programming%20a%20Chess%20Player.ipynb

perhaps sente have another example how to achieve it
tried before base on python chess notebook link above but my problem is when the human player turn input, it's hard to map it into sente move
e.g. using move = input("Move : "), when type 4,4 the machine think it's as string
when separate it 
x = int(input("X : ") )
y = int(input("Y : ") )
move = x, y
then it still raise an error

**Comment by atw1020** [comment]
Go has a standardized way of interacting with go programs called the [Go Text Protocol](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2.pdf) (GTP for short). The Sente [GTP module](https://sente.readthedocs.io/en/latest/GTP/introduction.html) includes utilities for interacting with GTP. GTP provides a command-line interface that works in the requested way. 

Example GTP interaction from the GTP docs:
```
>> play B D4
=

>> play W D16
=

>> showboard
19  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
18  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
17  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
16  .  .  .  O  .  .  .  .  .  *  .  .  .  .  .  *  .  .  .
15  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
14  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
13  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
12  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
11  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
10  .  .  .  *  .  .  .  .  .  *  .  .  .  .  .  *  .  .  .
 9  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 8  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 7  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 6  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 5  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 4  .  .  .  X  .  .  .  .  .  *  .  .  .  .  .  *  .  .  .
 3  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 2  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
 1  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
    A  B  C  D  E  F  G  H  J  K  L  M  N  O  P  Q  R  S  T
```

GTP can also be used to connect Sente to programs like [Sabaki](https://sabaki.yichuanshen.de) or KGS. Instructions can be found on the GTP docs to [connect sente to Sabaki](https://sabaki.yichuanshen.de)

**Comment by atw1020** [comment]
Looking at your code, I've also discovered you are running Sente < 0.3 and I should note that GTP support was added in sense 0.4, so you need to upgrade to gain access to the sense GTP features.
